serverInfo:
  host: 203.125.109.123
  port: 1883
  username: datafeed
  password: Datafeed#18

dataInfo:
  datachanged_bind_Key: datachanged
  datachanged_queue_name: price.img-fx.com_alantest
  datachanged_qos: 1

logFileName: datachanged.log

# Show console log : Enable/Disable - 1/0
debug: 1
